-- M3-1a Sub-Objective Framework + Gap Tracker MVP — additive only.
--
-- Sibling table to `contacts` (NOT extension of contact_objective_stack —
-- different semantics: stack = goals we pursue; this table = info we need
-- to learn). Three enums + table + 2 indexes + UNIQUE constraint for
-- idempotent seeding + cascading delete on contact + RESTRICT delete on
-- tenant (per feedback_destructive_db_operation_protocol + the PRD §3
-- storage decision).
--
-- Migrate-diff drift hygiene (per feedback_prisma_vector_index_silent_drop_drift):
--   - DROP INDEX "knowledge_chunk_embedding_hnsw_idx" was generated by
--     `prisma migrate diff` against prod and stripped from this artifact
--     (CI applying it would nuke the HNSW vector index, breaking Brain RAG).
--   - RenameIndex "tenant_objective_selection_*" also generated and
--     stripped (orthogonal drift not in this slice's scope; will be
--     resolved in its own follow-up).
-- Eyeballed clean before commit.

-- CreateEnum
CREATE TYPE "sub_objective_state" AS ENUM ('unknown', 'partial', 'known', 'not_applicable');

-- CreateEnum
CREATE TYPE "sub_objective_value_type" AS ENUM ('text', 'date', 'numeric', 'enum_value');

-- CreateEnum
CREATE TYPE "sub_objective_source" AS ENUM ('decision_initialize', 'manual', 'extraction', 'enrichment');

-- CreateTable
CREATE TABLE "contact_sub_objective_gap_state" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "contact_id" TEXT NOT NULL,
    "sub_objective_key" TEXT NOT NULL,
    "state" "sub_objective_state" NOT NULL DEFAULT 'unknown',
    "value_type" "sub_objective_value_type" NOT NULL,
    "value_text" TEXT,
    "value_date" TIMESTAMP(3),
    "value_numeric" DOUBLE PRECISION,
    "value_enum" TEXT,
    "source" "sub_objective_source" NOT NULL,
    "set_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "set_by" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "contact_sub_objective_gap_state_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "contact_sub_objective_gap_state_tenant_contact_idx" ON "contact_sub_objective_gap_state"("tenant_id", "contact_id");

-- CreateIndex
CREATE INDEX "contact_sub_objective_gap_state_tenant_key_state_idx" ON "contact_sub_objective_gap_state"("tenant_id", "sub_objective_key", "state");

-- CreateIndex
CREATE UNIQUE INDEX "contact_sub_objective_gap_state_unique" ON "contact_sub_objective_gap_state"("tenant_id", "contact_id", "sub_objective_key");

-- AddForeignKey
ALTER TABLE "contact_sub_objective_gap_state" ADD CONSTRAINT "contact_sub_objective_gap_state_contact_id_fkey" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "contact_sub_objective_gap_state" ADD CONSTRAINT "contact_sub_objective_gap_state_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
