/**
 * KAN-854 — GCS bucket for tenant assets (logos, future per-tenant uploads).
 *
 * Sibling Terraform PR for Account Page Cohort 2 (KAN-855). The bucket
 * holds tenant logo originals + the 256/128/64 Sharp-generated variants
 * under `tenants/{tenantId}/account/logo-{timestamp}-{size}.{ext}`. All
 * access from the browser flows through V4 signed URLs (PUT 15m, GET 1h)
 * generated by the API service — public_access_prevention = "enforced"
 * locks out direct anonymous access.
 *
 * Apply pattern (per `feedback_terraform_unmanaged_aspirational_state`,
 * mirrors api.tf header):
 *
 *   terraform plan -var project_id=growth-493400 -var region=us-central1 \
 *     -target=google_storage_bucket.growth_tenant_assets \
 *     -target=google_storage_bucket_iam_member.api_object_admin \
 *     -target=google_service_account_iam_member.api_self_token_creator
 *
 *   terraform apply -var project_id=growth-493400 -var region=us-central1 \
 *     -target=google_storage_bucket.growth_tenant_assets \
 *     -target=google_storage_bucket_iam_member.api_object_admin \
 *     -target=google_service_account_iam_member.api_self_token_creator
 *
 * Runtime SA: API service deploys without an explicit
 * `--service-account` flag (see deploy-api.yml :240+) which means Cloud
 * Run uses the project's default Compute SA. Per
 * `reference_pubsub_publish_iam_canonical_home`, the over-grant on the
 * shared Compute SA is the documented pre-launch posture; KAN-690
 * tracks the migration to a dedicated `growth-api` SA. When that lands,
 * update both bindings here to point at the dedicated SA.
 *
 * Sibling — connectors.tf:60 already manages a dedicated
 * `google_service_account.connectors` SA; the API side is the gap.
 */

# ─── Data — references to the existing default Compute SA ────────────
# Resolved at plan time so the binding follows the real SA identity, not
# a hardcoded email that could drift if the project ever migrates.

data "google_compute_default_service_account" "default" {
  project = var.project_id
}

# ─── google_storage_bucket — tenant assets ───────────────────────────
# Versioning + lifecycle: 30-day retention on non-current generations
# gives a recovery window for accidental "Replace logo" mistakes without
# unbounded storage growth. Spec §2 decision 2.

resource "google_storage_bucket" "growth_tenant_assets" {
  name          = "growth-tenant-assets"
  location      = "us-central1"
  project       = var.project_id
  storage_class = "STANDARD"

  # Lock down anonymous + IAM-policy-style ACL access — every read/write
  # flows through the API's V4 signed-URL helpers.
  public_access_prevention    = "enforced"
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }

  # Reap stale non-current generations after 30 days. The current
  # generation is never matched by `with_state = "ARCHIVED"` so live
  # logos stay forever; versioning lets a tenant recover an accidental
  # "Replace logo" within the 30-day window.
  lifecycle_rule {
    condition {
      age        = 30
      with_state = "ARCHIVED"
    }
    action {
      type = "Delete"
    }
  }

  labels = {
    app   = "growth"
    owner = "axisone-team"
  }

  # ─── CORS — browser-direct PUT for the V4 signed-URL upload flow ───
  # Without this block, the browser preflight (OPTIONS) and the body
  # PUT both fail with "Failed to fetch" because the bucket doesn't
  # return Access-Control-Allow-Origin matching the growth-web origin.
  # KAN-875 caught this at Cohort 2 logo-upload Chrome-MCP verification —
  # server-side mock-based unit tests don't exercise real browser CORS.
  #
  # Allowed methods restricted to PUT + OPTIONS (the V4 signed-URL
  # upload flow); GETs come back through API-issued read URLs and don't
  # cross the bucket boundary from the browser.
  #
  # When a custom domain (e.g., app.axisone.ca, growth.axisone.ca) is
  # mapped to the growth-web service, add it to the origin list. Until
  # then, both run.app URLs cover all reachable origins.
  cors {
    origin = [
      "https://growth-web-1086551891973.us-central1.run.app",
      "https://growth-web-biut5gfhuq-uc.a.run.app",
    ]
    method          = ["PUT", "OPTIONS"]
    response_header = ["Content-Type", "x-goog-meta-*"]
    max_age_seconds = 3600
  }
}

# ─── IAM — API runtime SA can read/write objects ─────────────────────
# objectAdmin (not just objectCreator) because the finalizeLogo path
# also reads back the original to drive Sharp variant generation, and
# the regenerateVariants recovery path re-reads the original.

resource "google_storage_bucket_iam_member" "api_object_admin" {
  bucket = google_storage_bucket.growth_tenant_assets.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${data.google_compute_default_service_account.default.email}"
}

# ─── IAM — API SA can self-impersonate for V4 signed URLs ────────────
# `signedUrl({ version: 'v4' })` in @google-cloud/storage requires the
# caller to mint an OAuth2 access token via signBlob, which in turn
# requires roles/iam.serviceAccountTokenCreator on the SA being signed
# *as*. Narrow binding: member = the API SA, resource = the API SA's
# IAM policy (self-impersonation only).
#
# Without this grant, signed-URL generation fails with:
#   PERMISSION_DENIED: ... iam.serviceAccountTokenCreator ...

resource "google_service_account_iam_member" "api_self_token_creator" {
  service_account_id = data.google_compute_default_service_account.default.name
  role               = "roles/iam.serviceAccountTokenCreator"
  member             = "serviceAccount:${data.google_compute_default_service_account.default.email}"
}

# ─── Output ──────────────────────────────────────────────────────────
# Surfaced for any downstream module that wants to reference the bucket
# by name (e.g., a future cleanup janitor cron).

output "tenant_assets_bucket_name" {
  value       = google_storage_bucket.growth_tenant_assets.name
  description = "GCS bucket holding tenant logos + variants. KAN-854."
}

# ═══════════════════════════════════════════════════════════════════════
# KAN-896 — Ingestion Cohort 2.1a (upload backend)
#
# Sibling bucket for tenant CSV/XLSX uploads. Same posture as
# growth-tenant-assets: V4-signed PUT (15min) + GET (1hr) only, no
# public access, CORS scoped to growth-web origins.
#
# Object layout: `tenants/{tenantId}/imports/{importJobId}/{filename}` —
# tenant-scope prefix check enforced in import-storage.ts before any
# mutation (mirrors isOwnedByTenant pattern from KAN-855 logos).
#
# Apply pattern (mirrors KAN-854):
#   terraform plan -target=google_storage_bucket.growth_tenant_imports \
#                  -target=google_storage_bucket_iam_member.api_object_admin_imports
#   terraform apply -target=google_storage_bucket.growth_tenant_imports \
#                   -target=google_storage_bucket_iam_member.api_object_admin_imports
#
# selfTokenCreator binding (api_self_token_creator above) covers signed-URL
# generation for ALL buckets the default SA accesses — no per-bucket
# duplication needed. Only the bucket-scoped objectAdmin grant is added
# here.
# ═══════════════════════════════════════════════════════════════════════

resource "google_storage_bucket" "growth_tenant_imports" {
  name          = "growth-tenant-imports"
  location      = "us-central1"
  project       = var.project_id
  storage_class = "STANDARD"

  # Lock down anonymous access; every read/write flows through the API's
  # V4 signed-URL helpers (PUT 15m, GET 1h).
  public_access_prevention    = "enforced"
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }

  # 30-day reaper for archived (non-current) generations. Live import
  # files are kept indefinitely so the future commit cohort (PR 8) can
  # replay parse on demand; archived versions only reflect file
  # replacements / re-uploads.
  lifecycle_rule {
    condition {
      age        = 30
      with_state = "ARCHIVED"
    }
    action {
      type = "Delete"
    }
  }

  labels = {
    app   = "growth"
    owner = "axisone-team"
  }

  # ─── CORS — browser-direct PUT for V4 signed-URL upload flow ──────
  # Mirrors the growth-tenant-assets CORS block (KAN-875). Restricted to
  # PUT + OPTIONS; reads come back through API-issued signed GET URLs.
  cors {
    origin = [
      "https://growth-web-1086551891973.us-central1.run.app",
      "https://growth-web-biut5gfhuq-uc.a.run.app",
    ]
    method          = ["PUT", "OPTIONS"]
    response_header = ["Content-Type", "x-goog-meta-*"]
    max_age_seconds = 3600
  }
}

# ─── IAM — API runtime SA can read/write objects in imports bucket ────
# objectAdmin (not just objectCreator) — the inspection helper downloads
# the uploaded object to parse headers + sample rows, then writes the
# detected metadata back to the ImportJob row (not GCS). Future
# duplicate-detection + commit cohorts will also re-read uploaded files.

resource "google_storage_bucket_iam_member" "api_object_admin_imports" {
  bucket = google_storage_bucket.growth_tenant_imports.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${data.google_compute_default_service_account.default.email}"
}

# selfTokenCreator binding NOT duplicated here — KAN-854's
# api_self_token_creator covers V4 signed-URL generation for the default
# SA across all buckets the SA accesses.

output "tenant_imports_bucket_name" {
  value       = google_storage_bucket.growth_tenant_imports.name
  description = "GCS bucket holding tenant CSV/XLSX upload originals. KAN-896."
}
