-- KAN-1042 PR A2 — extend sub_objective_source enum with 'engine'.
--
-- # Fix-forward 2026-06-01 17:20 UTC
--
-- Original SQL used the wrong identifier "SubObjectiveSource" (PascalCase
-- Prisma model name) instead of "sub_objective_source" (snake_case
-- Postgres type name per the @@map directive). PROD migrate deploy failed
-- with P3018 → DbError type "SubObjectiveSource" does not exist; deploy
-- lane wedged with a failed _prisma_migrations row blocking subsequent
-- deploys with P3009.
--
-- Recovery (authorized 2026-06-01 17:20 UTC):
--   1. Read-only verify confirmed PROD enum name is sub_objective_source
--      (4 values pre-fix) AND the failed migration row had finished_at
--      NULL.
--   2. `prisma migrate resolve --rolled-back
--      20260601164727_kan_1042_pr_a2_engine_source_enum` marked the failed
--      row as rolled-back (rolled_back_at populated). No DDL change —
--      only mutated the _prisma_migrations metadata table.
--   3. Fix-forward PR (this commit) keeps the SAME migration filename so
--      the resolve marker matches; corrects the SQL identifier to
--      "sub_objective_source"; next migrate deploy re-attempts and applies
--      cleanly.
--
-- Discipline pin (banked for future migrations): when a Prisma enum/model
-- has an @@map directive, the SQL identifier in raw migrations MUST use
-- the @@map'd value, NOT the Prisma model name. Every existing enum
-- migration in this repo (campaign_strategy, staging_status,
-- stage_outcome_type, service_price_unit, ...) followed this pattern.
-- Class-fix discipline miss — committed to feedback memo as
-- `feedback_prisma_at_map_vs_model_name_in_migration_sql`.
--
-- # Original intent
--
-- Enables engine-driven sub-objective transitions to record source-of-truth
-- at the column level, avoiding the "column lies" anti-pattern (per
-- `feedback_cast_loose_prisma_runtime_trap` + sibling memos). The
-- alternative — keeping the column hardcoded `'manual'` and threading the
-- engine discriminator only into the audit JSONB — would have the column
-- silently misrepresent state, creating cognitive overhead every time the
-- operator UI's "set by ..." render had to reconcile a column-says-manual
-- value against an actor field that says `engine_agentic_live`.
--
-- # Deploy semantics
--
-- `ALTER TYPE ... ADD VALUE` is non-transactional in Postgres — commits
-- independently of any surrounding transaction. The Prisma migrate engine
-- handles this correctly for additive enum extensions; no special wrapping
-- needed. New value is available immediately post-migration. No backfill
-- (no existing rows mutated). Old client code that doesn't know about
-- 'engine' continues to deserialize correctly on reads — it just sees an
-- unfamiliar string. Writes from old code paths continue to write 'manual'
-- (existing operator path) or 'decision_initialize' (existing seed path);
-- only the new PR A2 engine-driven dispatcher arm writes 'engine'.
--
-- # Drift-strip discipline (KAN-786 / KAN-787 / KAN-1034 / PR A1 history)
--
-- Hand-authored offline (no `prisma migrate dev` interactive path) to
-- avoid the standard spurious-DROP items. Same posture as PR A1's
-- additive Boolean migration at 20260601154508. Items typically stripped:
--
--   1. DROP INDEX "knowledge_chunk_embedding_hnsw_idx" — KAN-786 / KAN-787.
--      HNSW index is real + load-bearing; Prisma can't model it; auto-DROP
--      would silently nuke PROD's vector search. INTENTIONALLY OMITTED.
--
--   2. ALTER INDEX tenant_objective_selection_tenant_id_objective_id_…
--      RENAME TO …. KAN-1034 cosmetic rename; not load-bearing for any
--      code path. INTENTIONALLY OMITTED to keep this migration purely
--      additive to the sub_objective_source enum.

-- AlterEnum
ALTER TYPE "sub_objective_source" ADD VALUE 'engine';
